# Generated by Django 2.2.8 on 2019-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='home_display',
            field=models.BooleanField(default=False, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='column',
            name='nav_display',
            field=models.BooleanField(default=False, verbose_name='导航显示'),
        ),
    ]
